---
download: 
  # Scribes default output path is the users home directory.
  # On MAC scribe uses the $HOME enviornment variable
  # On Windows scribe uses the %USERPROFILE% variable.
  # If the user would like to use a different default output path the user can define that here.
  path: ~
  # If folderGeneration is set to TRUE scribe will parse the file name and create a folder to store the downloaded file in.
  # EX. The file Google-Resume.pdf, would be downloaded at 
  # C:\scribe\Google\Google-resume.pdf
  folderGeneration: true
  # if folderGeneration is set to TRUE and usePrefix is set to TRUE then a your download path for ex: "Google - Resume" would be $HOME\scribe\Google\Google - Resume.pdf
  # if folderGeneration is set to TRUE and usePrefix is set to FALSE then a your download path for ex: "Google - Resume" would be $HOME\scribe\Resume\Google - Resume.pdf
  # if folderGeneration is set to FALSE usePrefix is ignored
  usePrefix: false
credentials:
  # this is the default file name for the credentials file for the google docs API make sure that yours matches this as is located at this file path: ./docs/credentials.json
  docs: credentials.json
  # this is the default file name for the credentials file for the google drive API make sure that yours matches this as is located at this file path: ./drive/credentials.json
  drive: credentials.json
  # this is the default file name for the credentials file for the google sheets API make sure that yours matches this as is located at this file path: ./sheets/credentials.json
  sheets: credentials.json